exports.Pixaxe = [
    
    {'Name' : '나무 곡괭이', 'Code' : 'P0', 'Rank' : '일반'}, 
    {'Name' : '돌 곡괭이', 'Code' : 'P1', 'Rank' : '일반'},
    {'Name' : '철 곡괭이', 'Code' : 'P2', 'Rank' : '일반'},
    {'Name' : '금 곡괭이', 'Code' : 'P3', 'Rank' : '일반'}

]

exports.Minerals = [
    
        {'Name' : '돌', 'Rank' : '일반', 'Code' : 'MF0', 'Cost' : 11},
        {'Name' : '조약돌', 'Rank' : '일반', 'Code' : 'MF1', 'Cost' : 8},
        {'Name' : '석탄', 'Rank' : '일반', 'Code' : 'MF2', 'Cost' : 10},
        {'Name' : '구리', 'Rank' : '일반', 'Code' : 'MF3', 'Cost' : 16},
        {'Name' : '납', 'Rank' : '일반', 'Code' : 'MF4', 'Cost' : 14},
        {'Name' : '아연', 'Rank' : '일반', 'Code' : 'MF5', 'Cost' : 18},
        {'Name' : '철', 'Rank' : '일반', 'Code' : 'MF6', 'Cost' : 21},
        {'Name' : '망간', 'Rank' : '일반', 'Code' : 'MF7', 'Cost' : 20},
        {'Name' : '주석', 'Rank' : '일반', 'Code' : 'MF8', 'Cost' : 27},
        {'Name' : '석회석', 'Rank' : '일반', 'Code' : 'MF9', 'Code' : 31},   
        {'Name' : '규석', 'Rank' : '일반', 'Code' : 'MF10', 'Cost' : 31},
        {'Name' : '장석', 'Rank' : '일반', 'Code' : 'MF11', 'Cost' : 25},
        {'Name' : '방해석', 'Rank' : '일반', 'Code' : 'MF12', 'Cost' : 17},
        {'Name' : '고령토', 'Rank' : '일반', 'Code' : 'MF13', 'Cost' : 23},
        {'Name' : '운모', 'Rank' : '일반', 'Code' : 'MF14', 'Cost' :24 },
        {'Name' : '활석', 'Rank' : '일반', 'Code' : 'MF15', 'Cost' : 24},
        {'Name' : '불석', 'Rank' : '일반', 'Code' : 'MF16', 'Cost' :27},
        {'Name' : '규조토', 'Rank' : '일반', 'Code' : 'MF17', 'Cost' :27},
        {'Name' : '규회석', 'Rank' : '일반', 'Code' : 'MF18', 'Cost' :33},
        {'Name' : '명반석', 'Rank' : '일반', 'Code' : 'MF19', 'Cost' : 37},   
        {'Name' : '사문석', 'Rank' : '일반', 'Code' : 'MF20', 'Cost' : 29},
        {'Name' : '석면', 'Rank' : '일반', 'Code' : 'MF21', 'Cost' : 43},
        {'Name' : '석영', 'Rank' : '일반', 'Code' : 'MF22', 'Cost' : 37},
        {'Name' : '자수정', 'Rank' : '일반', 'Code' : 'MF23', 'Cost' : 39},
        {'Name' : '중정석', 'Rank' : '일반', 'Code' : 'MF24', 'Cost' : 38},
        {'Name' : '홍주석', 'Rank' : '일반', 'Code' : 'MF25', 'Cost' : 30},
        {'Name' : '흑철석', 'Rank' : '일반', 'Code' : 'MF26', 'Cost' :32},  
        {'Name' : '흑연', 'Rank' : '일반', 'Code' : 'MF0', 'Cost' : 43},   
        {'Name' : '은', 'Rank' : '희귀', 'Code' : 'MG0', 'Cost' : 131},
        {'Name' : '금', 'Rank' : '희귀', 'Code' : 'MG1', 'Cost' : 161},
        {'Name' : '아다만티움', 'Rank' : '희귀', 'Code' : 'MG2', 'Cost' : 132},
        {'Name' : '다이아몬드', 'Rank' : '희귀', 'Code' : 'MG3', 'Cost' : 234},
        {'Name' : '백금', 'Rank' : '희귀', 'Code' : 'MG4', 'Cost' : 221},
        {'Name' : '가넷', 'Rank' : '희귀', 'code' : 'MG5', 'Cost' :184},
        {'Name' : '사파이어', 'Rank' : '희귀', 'Code' : 'MG6', 'Cost' : 251},
        {'Name' : '에메랄드', 'Rank' : '희귀', 'Code' : 'MG7', 'Cost' : 246},
        {'Name' : '연옥', 'Rank' : '희귀', 'Code' : 'MG9', 'Cost' : 253},
        {'Name' : '미스릴', 'Rank' : '희귀', 'Code' : 'MG10', 'Cost' : 267},   
        {'Name' : '알루미늄', 'Rank' : '초희귀', 'Code' : 'MF0', 'Cost' : },
        {'Name' : '니켈', 'Rank' : '초희귀', 'Code' : 'MF1', 'Cost' : },
        {'Name' : '탄산나트륨', 'Rank' : '초희귀', 'Code' : 'MF2', 'Cost' : },
        {'Name' : '인', 'Rank' : '초희귀', 'Code' : 'MF3', 'Cost' : },
        {'Name' : '칼슘카보네이트', 'Rank' : '초희귀', 'Code' : 'MF4', 'Cost' : },
        {'Name' : '유연석고', 'Rank' : '초희귀', 'code' : 'MF5', 'Cost' : },
        {'Name' : '우라늄', 'Rank' : '초희귀', 'Code' : 'MF6', 'Cost' : },
        {'Name' : '크롬', 'Rank' : '초희귀', 'Code' : 'MF7', 'Cost' : },
        {'Name' : '플래티넘', 'Rank' : '초희귀', 'Code' : 'MF8', 'Cost' : },
        {'Name' : '루테늄', 'Rank' : '초희귀', 'Code' : 'MF9', 'Cost' : },    
        {'Name' : '코발트', 'Rank' : '영웅', 'Code' : 'ME0', 'Cost' : },
        {'Name' : '리튬', 'Rank' : '영웅', 'Code' : 'ME1', 'Cost' : },
        {'Name' : '오리하르콘', 'Rank' : '영웅', 'Code' : 'ME2', 'Cost' : },
        {'Name' : '금강석', 'Rank' : '영웅', 'Code' : 'ME3', 'Cost' : },
        {'Name' : '흑요석', 'Rank' : '영웅', 'Code' : 'ME4', 'Cost' : },
        {'Name' : '쿤자이트', 'Rank' : '영웅', 'Code' : 'ME5', 'Cost' : },
        {'Name' : '티타늄', 'Rank' : '영웅', 'Code' : 'ME6', 'Cost' : },
        {'Name' : '아메트린', 'Rank' : '영웅', 'Code' :'ME7', 'Cost' :  },
        {'Name' : '레드 사파이어', 'Rank' : '영웅', 'Code' : 'ME8', 'Cost' : },
        {'Name' : '영석', 'Rank' : '영웅', 'Code' : 'ME10', 'Cost' : },     
        {'Name' : '로들라이트', 'Rank' : '전설', 'Code' : 'MD0', 'Cost' : },
        {'Name' : '핑크다이아몬드', 'Rank' : '전설', 'Code' : 'MD1', 'Cost' : },
        {'Name' : '레드 다이아몬드', 'Rank' : '전설', 'Code' : 'MD2', 'Cost' : },
        {'Name' : '스피넬', 'Rank' : '전설', 'Code' : 'MD3', 'Cost' : },
        {'Name' : '지르콘', 'Rank' : '전설', 'Code' : 'MD4', 'Cost' : },
        {'Name' : '머스그레이비트', 'Rank' : '전설', 'Code' : 'MD5'},
        {'Name' : '헤소나이트', 'Rank' : '전설', 'Code' : 'MD6'},
        {'Name' : '파이어 오팔', 'Rank' : '전설', 'Code' : 'MD7'},
        {'Name' : '데만토이드가넷', 'Rank' : '전설', 'Code' : 'MD8'},
        {'Name' : '레인보우 다이아몬드', 'Rank' : '전설', 'Code' : 'MD9', 'Cost' : },   
        {'Name' : '고대생물', 'Rank' : '초월', 'Code' : 'MC0', 'Cost' : },
        {'Name' : '운석', 'Rank' : '초월', 'Code' : 'MC1', 'Cost' : },
        {'Name' : '특별한 조각', 'Rank' : '초월', 'Code' : 'MC2', 'Cost' : },
        {'Name' : '은하수', 'Rank' : '초월', 'code' : 'MC3', 'Cost' : },
        {'Name' : '공허', 'Rank' : '초월', 'Code' : 'MC4', 'Cost' : },
        {'Name' : '특별한 돌', 'Rank' : '초월', 'code' : 'MC5', 'Cost' : },
        {'Name' : '균열의 돌', 'Rank' : '초월', 'Code' : 'MC6', 'Cost' : },
        {'Name' : '고대의 책', 'Rank' : '초월', 'Code' : 'MC7', 'Cost' : },
        {'Name' : 'UFO', 'Rank' : '초월', 'Code' : 'MC8', 'Cost' : },
        {'Name' : '녹아버린 돌', 'Rank' : '초월', 'Code' : 'MC9', 'Cost' : },    
        {'Name' : '우주 조각', 'Rank' : '영원', 'Code' : 'MB0', 'Cost' : },
        {'Name' : '행성의 파편', 'Rank' : '영원', 'Code' : 'MB1', 'Cost' : 7196},
        {'Name' : '시공주머니', 'Rank' : '영원', 'Code' : 'MB2', 'Cost' : },
        {'Name' : '???', 'Rank' : '영원', 'Code' : 'MB3', 'Cost' : },    
        {'Name' : '불의 조각', 'Rank' : '불멸', 'Code' : 'MA0', 'Cost' : 17857},
        {'Name' : '???의 심장', 'Rank' : '불멸', 'Code' : 'MA1', 'Cost' : },
        {'Name' : '영혼 조각', 'Rank' : '불멸', 'Code' : 'MA2', 'Cost' : }
    
];

exports.LvL = [ //칭호
    {'Name' : '뉴비', 'Lv' : 1, 'M_time' : 25, 'H_time' : 20, 'Max_H' : 10},
    {'Name' : '초보자', 'Lv' : 10, 'M_time' : 21, 'H_time' : 27, 'Max_H' : 15},
    {'Name' : '중급자', 'Lv' : 10, 'M_time' : 21, 'H_time' : 25, 'Max_H' : 120}
]; //레벨별 정보


/*   일반-희귀-초희귀-영웅-전설-초월-영원-불멸
      H    G    F     E    D   C    B   A         */